version: 0.1.{build}

platform:
  - x64


init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm view electron version
  - npm run pack:win

test: off
