version: 0.1.{build}

platform:
  - x64
  
cache:		
 - node_modules		
 - app\node_modules		
 - '%APPDATA%\npm-cache'		
 - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm view electron version
  - npm view electron-builder version
  - npm run pack:win

test: off
